# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hack on GitHub Pages
description: >
  This site will get you started hacking with GitHub Pages.
baseurl: "/tamuhack" # the subpath of your site
url: "https://ntiner1.github.io/tamuhack/"
email: ntiner1@tamu.edu
github_username:  ntiner1
linkedin_username: ntiner1
twitter_username: ntiner1

# Build settings
markdown: kramdown
sass:
    style: :compressed
